name: HashiCorp Sentinel workflow for Terraform

on:
  push:
    branches:
      - dev

jobs:
  policy-as-code:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check-out source code
        uses: actions/checkout@v4
      # - name: Install Terraform CLI
      #   uses: hashicorp/setup-terraform@v3
      # - name: Install Sentinel CLI
      #   run: |
      #     FILENAME="sentinel_${{ env.SENTINEL_VERSION }}_linux_amd64.zip"
      #     wget "https://releases.hashicorp.com/sentinel/${{ env.SENTINEL_VERSION }}/$FILENAME"
      #     unzip "$FILENAME" -d $HOME/bin
      #     chmod +x $HOME/bin/sentinel
      #     echo "$HOME/bin" >> $GITHUB_PATH
      - name: Initialize Terraform configuration
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      - name: Run Terraform plan
        run: terraform plan -out tfplan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      - name: Create JSON plan for Sentinel
        run: terraform show -json tfplan | jq > plan.json
      - name: Run Sentinel and store the result as JSON
        run: sentinel apply
